### ISSUE TITLE
API Sign up link is broken

### ISSUE THREAD

**Issue by kpconnell** [jcconnell/python-magicseaweed#3]
The link in the readme to sign up for an API key gets a 404.

**Comment by jcconnell** [comment]
Looks like https://magicseaweed.com/docs/api/60/ is the new link. I can update it. Also welcome to submit a merge request I'd you'd like to do it before I get to it.

**Comment by kpconnell** [comment]
Ya except that doesn't tell you how to sign up to get get a key and they are not publishing info on how to do that and so a library that uses an api you can't get access to is... well... not super useful.

**Comment by jcconnell** [comment]
Looks like you'll need to email them for an API key: https://magicseaweed.com/news/msw-surf-forecast-api/5279/

**Comment by kpconnell** [comment]
I heard back from them, they do not give out api keys anymore.....   you
might want to notate that.
